### PR TITLE
Fixed notebooks and YAML files; added a pyproject.toml for compatibility with poetry

### PR DESCRIPTION
**Pull request by NormannR**

### CODE REVIEW

**Comment by albop** [comment]
The pyproject.toml is a nice touch. It is a way to require the right version from dolo and dolark. But in this instance, it complicates stuff a little bit, because we have jupyter notebooks. The kernels need to have the right versions of the library, and I"m not sure how we can ensure that.

**Comment by NormannR** [comment]
It is possible to run ipykernel within the poetry environment  and the dependencies are properly shared. In VSCode, for example, choosing the poetry environment interpreter works well on my computer.

**Comment by albop** [comment]
Ok, I'll test. I thought the ipykernels were shared by the session and
indépendent from the environments (each kernel activating it's own
environment)

**Comment by NormannR** [comment]
I thought too, but it ended up working without manipulation. Otherwise, adding the environment to the kernelspec through  a `python -m ipykernel install --user --name=myenv` or modifying the `kernel.json` file should do the trick.

I only modified the notebooks. If they are validated, I shall export them to the .py format before the PR is merged.

**Pull request merged**
